### ISSUE TITLE
Older Versions Not Working.

### ISSUE THREAD

**Issue by Vistekk** [Zi0MIX/bo2_songsr_patch#1]
Hi Zi0. I tried using v5.1 of the song patch but it didn't work. (for Nuketown song. ZWR doesn't allow a population counter) It has been renamed to "joke.gsc" and after inserting the gsc file into plutonium it doesn't function. Is there something I'm doing wrong?

**Comment by Zi0MIX** [comment]
That's not a problem with the patch, just use most recent version from releases. If ZR doesn't allow it they should probably be told that song community does

**Comment by Vistekk** [comment]
ok ty
